/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT2_RMIISRC_EXTAL 0x00u  /*!<@brief RMII clock source select: EXTAL clock */
#define SOPT4_FTM2CH0SRC_FTM 0x00u /*!<@brief FTM2 channel 0 input capture source select: FTM2_CH0 signal */

/*! @name PORTC5 (number 77), SPI0_SCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SPI0_SCLK_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SPI0_SCLK_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_SCLK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_SCLK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_SCLK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name ADC0_DP3 (number 20), LINECAM_IN
  @{ */
/* @} */

/*! @name PORTC0 (number 70), LSC2_CSn
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LSC2_CSn_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LSC2_CSn_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LSC2_CSn_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LSC2_CSn_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LSC2_CSn_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE26 (number 33), DEBUG_OUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DEBUG_OUT_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DEBUG_OUT_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_OUT_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_OUT_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_OUT_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTC9 (number 81), DILSW1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DILSW1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DILSW1_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DILSW1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DILSW1_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DILSW1_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC10 (number 82), DILSW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DILSW2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DILSW2_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DILSW2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DILSW2_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DILSW2_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC11 (number 83), DILSW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DILSW3_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DILSW3_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DILSW3_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DILSW3_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DILSW3_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC12 (number 84), DILSW4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DILSW4_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DILSW4_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DILSW4_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DILSW4_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DILSW4_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC6 (number 78), DEBUG_OUT2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DEBUG_OUT2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DEBUG_OUT2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_OUT2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_OUT2_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_OUT2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTE6 (number 7), SD_DETECT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SD_DETECT_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SD_DETECT_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SD_DETECT_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SD_DETECT_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SD_DETECT_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTB20 (number 66), LED1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED1_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED1_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED1_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED1_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED1_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB21 (number 67), LED2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED2_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED2_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED2_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED2_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB22 (number 68), LED3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED3_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED3_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED3_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED3_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED3_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB23 (number 69), LED4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED4_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED4_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED4_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED4_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED4_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC16 (number 90), PB1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PB1_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PB1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PB1_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PB1_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PB1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC17 (number 91), PB2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PB2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PB2_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PB2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PB2_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PB2_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTA12 (number 42), MOTA_ENC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTA_ENC_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTA_ENC_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTA_ENC_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTA_ENC_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTA_ENC_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA13 (number 43), MOTB_ENC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTB_ENC_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTB_ENC_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTB_ENC_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTB_ENC_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTB_ENC_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC18 (number 92), E_STOP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_E_STOP_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_E_STOP_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_E_STOP_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_E_STOP_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_E_STOP_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
